Section "ServerFlags"
    Option "AutoAddGPU" "false"
EndSection

Section "Module"
    Disable "glx"
    Disable "dri"
    Disable "dri2"
    Disable "dri3"
EndSection

Section "Device"
    Identifier "fbdev"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device "fbdev"
EndSection
