Section "ServerFlags"
    Option "AutoAddGPU" "false"
    Option "AutoAddDevices" "false"
    Option "AllowEmptyInput" "true"
EndSection

Section "InputDevice"
    Identifier "keyboard0"
    Driver "evdev"
    Option "Device" "/dev/input/event0"
EndSection

Section "Module"
    Disable "glx"
    Disable "dri"
    Disable "dri2"
    Disable "dri3"
EndSection

Section "Device"
    Identifier "fbdev"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device "fbdev"
EndSection

Section "ServerLayout"
    Identifier "Layout0"
    Screen "Screen0"
    InputDevice "keyboard0" "CoreKeyboard"
EndSection
